executable            = /eos/home-s/snandaku/Higgscharmnew/higgscharm/condor/submit.sh
arguments             = $(JOBNUM) /eos/home-s/snandaku/Higgscharmnew/higgscharm /afs/cern.ch/user/s/snandaku/private/x509up_u178308
output                = /eos/home-s/snandaku/Higgscharmnew/higgscharm/condor/logs/hplusc_mva_4class_ctag2d/2023postBPix/EGamma1v1D/hplusc_mva_4class_ctag2d_EGamma1v1D.$(ClusterId).$(ProcId).out
error                 = /eos/home-s/snandaku/Higgscharmnew/higgscharm/condor/logs/hplusc_mva_4class_ctag2d/2023postBPix/EGamma1v1D/hplusc_mva_4class_ctag2d_EGamma1v1D.$(ClusterId).$(ProcId).err
log                   = /eos/home-s/snandaku/Higgscharmnew/higgscharm/condor/logs/hplusc_mva_4class_ctag2d/2023postBPix/EGamma1v1D/hplusc_mva_4class_ctag2d_EGamma1v1D.$(ClusterId).$(ProcId).log

should_transfer_files = YES
transfer_input_files  = /eos/home-s/snandaku/Higgscharmnew/higgscharm/condor/hplusc_mva_4class_ctag2d/2023postBPix/EGamma1v1D/partitions.json,/eos/home-s/snandaku/Higgscharmnew/higgscharm/condor/hplusc_mva_4class_ctag2d/2023postBPix/EGamma1v1D/jobnum.txt,/eos/home-s/snandaku/Higgscharmnew/higgscharm/condor/hplusc_mva_4class_ctag2d/2023postBPix/EGamma1v1D/arguments.json

+JobFlavour           = "longlunch"
+SingularityImage     = "/cvmfs/unpacked.cern.ch/registry.hub.docker.com/coffeateam/coffea-base-almalinux9:0.7.30-py3.10"

Queue JOBNUM from /eos/home-s/snandaku/Higgscharmnew/higgscharm/condor/hplusc_mva_4class_ctag2d/2023postBPix/EGamma1v1D/jobnum.txt