executable            = /afs/cern.ch/user/s/snandaku/Higgscharmnew/higgscharm/condor/submit.sh
arguments             = $(JOBNUM) /afs/cern.ch/user/s/snandaku/Higgscharmnew/higgscharm /afs/cern.ch/user/s/snandaku/private/x509up_u178308
output                = /afs/cern.ch/user/s/snandaku/Higgscharmnew/higgscharm/condor/logs/hplusc_mva_changes/2023preBPix/GluGlutoContinto2Zto4E/hplusc_mva_changes_GluGlutoContinto2Zto4E.$(ClusterId).$(ProcId).out
error                 = /afs/cern.ch/user/s/snandaku/Higgscharmnew/higgscharm/condor/logs/hplusc_mva_changes/2023preBPix/GluGlutoContinto2Zto4E/hplusc_mva_changes_GluGlutoContinto2Zto4E.$(ClusterId).$(ProcId).err
log                   = /afs/cern.ch/user/s/snandaku/Higgscharmnew/higgscharm/condor/logs/hplusc_mva_changes/2023preBPix/GluGlutoContinto2Zto4E/hplusc_mva_changes_GluGlutoContinto2Zto4E.$(ClusterId).$(ProcId).log

should_transfer_files = YES
transfer_input_files  = /afs/cern.ch/user/s/snandaku/Higgscharmnew/higgscharm/condor/hplusc_mva_changes/2023preBPix/GluGlutoContinto2Zto4E/partitions.json,/afs/cern.ch/user/s/snandaku/Higgscharmnew/higgscharm/condor/hplusc_mva_changes/2023preBPix/GluGlutoContinto2Zto4E/jobnum.txt,/afs/cern.ch/user/s/snandaku/Higgscharmnew/higgscharm/condor/hplusc_mva_changes/2023preBPix/GluGlutoContinto2Zto4E/arguments.json

+JobFlavour           = "longlunch"
+SingularityImage     = "/cvmfs/unpacked.cern.ch/registry.hub.docker.com/coffeateam/coffea-base-almalinux9:0.7.30-py3.10"

Queue JOBNUM from /afs/cern.ch/user/s/snandaku/Higgscharmnew/higgscharm/condor/hplusc_mva_changes/2023preBPix/GluGlutoContinto2Zto4E/jobnum.txt