executable            = /eos/home-s/snandaku/Higgscharmnew/higgscharm/condor/submit.sh
arguments             = $(JOBNUM) /eos/home-s/snandaku/Higgscharmnew/higgscharm /afs/cern.ch/user/s/snandaku/private/x509up_u178308
output                = /eos/home-s/snandaku/Higgscharmnew/higgscharm/condor/logs/hplusc_mva_4class_ctag2d/2023postBPix/GluGlutoContinto2Zto4E/hplusc_mva_4class_ctag2d_GluGlutoContinto2Zto4E.$(ClusterId).$(ProcId).out
error                 = /eos/home-s/snandaku/Higgscharmnew/higgscharm/condor/logs/hplusc_mva_4class_ctag2d/2023postBPix/GluGlutoContinto2Zto4E/hplusc_mva_4class_ctag2d_GluGlutoContinto2Zto4E.$(ClusterId).$(ProcId).err
log                   = /eos/home-s/snandaku/Higgscharmnew/higgscharm/condor/logs/hplusc_mva_4class_ctag2d/2023postBPix/GluGlutoContinto2Zto4E/hplusc_mva_4class_ctag2d_GluGlutoContinto2Zto4E.$(ClusterId).$(ProcId).log

should_transfer_files = YES
transfer_input_files  = /eos/home-s/snandaku/Higgscharmnew/higgscharm/condor/hplusc_mva_4class_ctag2d/2023postBPix/GluGlutoContinto2Zto4E/partitions.json,/eos/home-s/snandaku/Higgscharmnew/higgscharm/condor/hplusc_mva_4class_ctag2d/2023postBPix/GluGlutoContinto2Zto4E/jobnum.txt,/eos/home-s/snandaku/Higgscharmnew/higgscharm/condor/hplusc_mva_4class_ctag2d/2023postBPix/GluGlutoContinto2Zto4E/arguments.json

+JobFlavour           = "longlunch"
+SingularityImage     = "/cvmfs/unpacked.cern.ch/registry.hub.docker.com/coffeateam/coffea-base-almalinux9:0.7.30-py3.10"

Queue JOBNUM from /eos/home-s/snandaku/Higgscharmnew/higgscharm/condor/hplusc_mva_4class_ctag2d/2023postBPix/GluGlutoContinto2Zto4E/jobnum.txt